/*
 * generated by Xtext 2.9.1
 */
package org.xtext.example.mydsl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.mydsl.parser.antlr.internal.InternalFormValidationParser;
import org.xtext.example.mydsl.services.FormValidationGrammarAccess;

public class FormValidationParser extends AbstractAntlrParser {

	@Inject
	private FormValidationGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalFormValidationParser createParser(XtextTokenStream stream) {
		return new InternalFormValidationParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "ValidationClass";
	}

	public FormValidationGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(FormValidationGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
