/*
 * generated by Xtext 2.9.1
 */
package org.xtext.example.mydsl.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.example.FormValidationDsl.ui.internal.FormValidationDslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class FormValidationDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FormValidationDslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return FormValidationDslActivator.getInstance().getInjector(FormValidationDslActivator.ORG_XTEXT_EXAMPLE_MYDSL_FORMVALIDATIONDSL);
	}
	
}
