/**
 *
 * $Id$
 */
package classDiagram.validation;

import classDiagram.AccessModifier;
import classDiagram.Classifier;
import classDiagram.ElementType;

/**
 * A sample validator interface for {@link classDiagram.Attribute}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AttributeValidator {
	boolean validate();

	boolean validateIsStatic(boolean value);
	boolean validateType(ElementType value);

	boolean validateType(Classifier value);
	boolean validateAccessModifier(AccessModifier value);
}
