/**
 *
 * $Id$
 */
package classDiagram.validation;

import classDiagram.AccessModifier;
import classDiagram.Attribute;
import classDiagram.Method;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link classDiagram.Class}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ClassValidator {
	boolean validate();

	boolean validateFields(EList<Attribute> value);
	boolean validateIsAbstract(boolean value);
	boolean validateSupertypes(EList<classDiagram.Class> value);
	boolean validateSubtypes(EList<classDiagram.Class> value);
	boolean validateIsStatic(boolean value);
	boolean validateAccessModifier(AccessModifier value);
	boolean validateMethods(EList<Method> value);
}
