/**
 *
 * $Id$
 */
package classDiagram.validation;

import classDiagram.AccessModifier;
import classDiagram.Attribute;
import classDiagram.Classifier;

import classDiagram.ElementType;
import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link classDiagram.Method}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MethodValidator {
	boolean validate();

	boolean validateReturnType(ElementType value);

	boolean validateReturnType(Classifier value);
	boolean validateParameters(EList<Attribute> value);
	boolean validateAccessModifier(AccessModifier value);
	boolean validateIsStatic(boolean value);
	boolean validateIsAbstract(boolean value);
	boolean validateBody(String value);
}
