/**
 *
 * $Id$
 */
package er.validation;

import er.Domain;

/**
 * A sample validator interface for {@link er.AttributeDomain}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AttributeDomainValidator {
	boolean validate();

	boolean validateDomain(Domain value);
	boolean validateDefault(String value);
	boolean validateLength(int value);
}
