/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.mydsl;

import org.xtext.example.mydsl.FormValidationStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class FormValidationStandaloneSetup extends FormValidationStandaloneSetupGenerated {
  public static void doSetup() {
    FormValidationStandaloneSetup _formValidationStandaloneSetup = new FormValidationStandaloneSetup();
    _formValidationStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
