/*
 * generated by Xtext
 */
package org.xtext.example.domij.ui.contentassist

import org.xtext.example.domij.ui.contentassist.AbstractErDslProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class ErDslProposalProvider extends AbstractErDslProposalProvider {
}
