/**
 *
 * $Id$
 */
package rdbms.validation;

import org.eclipse.emf.common.util.EList;

import rdbms.CheckCon;
import rdbms.Column;
import rdbms.ForeignKey;
import rdbms.PrimaryKeyCon;
import rdbms.UniqueCon;

/**
 * A sample validator interface for {@link rdbms.Table}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TableValidator {
	boolean validate();

	boolean validateTableFKs(EList<ForeignKey> value);
	boolean validateTablePK(PrimaryKeyCon value);
	boolean validateTableUQ(EList<UniqueCon> value);
	boolean validateColumns(EList<Column> value);
	boolean validateTableCHs(EList<CheckCon> value);
}
