/**
 *
 * $Id$
 */
package er.validation;

import er.EntityConcept;
import er.MaxCardinality;
import er.MinCardinality;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link er.Categories}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CategoriesValidator {
	boolean validate();

	boolean validateEntities(EList<EntityConcept> value);
	boolean validateMin(MinCardinality value);
	boolean validateMax(MaxCardinality value);
}
