/**
 *
 * $Id$
 */
package er.validation;

import er.Attribute;
import er.Entity;
import er.RegularEntity;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link er.ISA}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ISAValidator {
	boolean validate();

	boolean validateSupertype(RegularEntity value);
	boolean validateSubtypes(EList<Entity> value);
	boolean validateClassificationAttribute(Attribute value);
}
