/*
 * generated by Xtext 2.9.1
 */
package org.xtext.example.mydsl.ide.contentassist.antlr;

import com.google.inject.Inject;
import java.util.Collection;
import java.util.HashMap;
import java.util.Map;
import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ide.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;
import org.xtext.example.mydsl.ide.contentassist.antlr.internal.InternalFormValDSLParser;
import org.xtext.example.mydsl.services.FormValDSLGrammarAccess;

public class FormValDSLParser extends AbstractContentAssistParser {

	@Inject
	private FormValDSLGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalFormValDSLParser createParser() {
		InternalFormValDSLParser result = new InternalFormValDSLParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getClassRuleAccess().getAlternatives(), "rule__ClassRule__Alternatives");
					put(grammarAccess.getFormLayoutAccess().getAlternatives(), "rule__FormLayout__Alternatives");
					put(grammarAccess.getAdditionalSettingsAccess().getAlternatives(), "rule__AdditionalSettings__Alternatives");
					put(grammarAccess.getAttributeRuleAccess().getAlternatives(), "rule__AttributeRule__Alternatives");
					put(grammarAccess.getUIComponentAccess().getAlternatives(), "rule__UIComponent__Alternatives");
					put(grammarAccess.getAttributeDataTypeAccess().getAlternatives(), "rule__AttributeDataType__Alternatives");
					put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
					put(grammarAccess.getEBooleanAccess().getAlternatives(), "rule__EBoolean__Alternatives");
					put(grammarAccess.getEDoubleAccess().getAlternatives_4_0(), "rule__EDouble__Alternatives_4_0");
					put(grammarAccess.getEUINumberComponentTypeAccess().getAlternatives(), "rule__EUINumberComponentType__Alternatives");
					put(grammarAccess.getEOrientationAccess().getAlternatives(), "rule__EOrientation__Alternatives");
					put(grammarAccess.getEDateUITypeAccess().getAlternatives(), "rule__EDateUIType__Alternatives");
					put(grammarAccess.getEPositionAccess().getAlternatives(), "rule__EPosition__Alternatives");
					put(grammarAccess.getEDataTypeAccess().getAlternatives(), "rule__EDataType__Alternatives");
					put(grammarAccess.getEGridOrderAccess().getAlternatives(), "rule__EGridOrder__Alternatives");
					put(grammarAccess.getERequiredFieldAccess().getAlternatives(), "rule__ERequiredField__Alternatives");
					put(grammarAccess.getBusinessModelAccess().getGroup(), "rule__BusinessModel__Group__0");
					put(grammarAccess.getBusinessModelAccess().getGroup_2(), "rule__BusinessModel__Group_2__0");
					put(grammarAccess.getBusinessModelAccess().getGroup_3(), "rule__BusinessModel__Group_3__0");
					put(grammarAccess.getBusinessModelAccess().getGroup_4(), "rule__BusinessModel__Group_4__0");
					put(grammarAccess.getValidationClassAccess().getGroup(), "rule__ValidationClass__Group__0");
					put(grammarAccess.getValidationClassAccess().getGroup_3(), "rule__ValidationClass__Group_3__0");
					put(grammarAccess.getValidationClassAccess().getGroup_4(), "rule__ValidationClass__Group_4__0");
					put(grammarAccess.getValidationClassAccess().getGroup_5(), "rule__ValidationClass__Group_5__0");
					put(grammarAccess.getValidationClassAccess().getGroup_6(), "rule__ValidationClass__Group_6__0");
					put(grammarAccess.getValidationClassAccess().getGroup_7(), "rule__ValidationClass__Group_7__0");
					put(grammarAccess.getClassAttributeAccess().getGroup(), "rule__ClassAttribute__Group__0");
					put(grammarAccess.getClassAttributeAccess().getGroup_2(), "rule__ClassAttribute__Group_2__0");
					put(grammarAccess.getClassAttributeAccess().getGroup_6(), "rule__ClassAttribute__Group_6__0");
					put(grammarAccess.getOverviewSettingsAccess().getGroup(), "rule__OverviewSettings__Group__0");
					put(grammarAccess.getAttributeTypeAccess().getGroup(), "rule__AttributeType__Group__0");
					put(grammarAccess.getNumericUIComponentAccess().getGroup(), "rule__NumericUIComponent__Group__0");
					put(grammarAccess.getNumericUIComponentAccess().getGroup_3(), "rule__NumericUIComponent__Group_3__0");
					put(grammarAccess.getNumericUIComponentAccess().getGroup_4(), "rule__NumericUIComponent__Group_4__0");
					put(grammarAccess.getNumericUIComponentAccess().getGroup_5(), "rule__NumericUIComponent__Group_5__0");
					put(grammarAccess.getNumericUIComponentAccess().getGroup_6(), "rule__NumericUIComponent__Group_6__0");
					put(grammarAccess.getRadioButtonAccess().getGroup(), "rule__RadioButton__Group__0");
					put(grammarAccess.getRadioButtonAccess().getGroup_3(), "rule__RadioButton__Group_3__0");
					put(grammarAccess.getRadioButtonAccess().getGroup_4(), "rule__RadioButton__Group_4__0");
					put(grammarAccess.getRadioButtonAccess().getGroup_5(), "rule__RadioButton__Group_5__0");
					put(grammarAccess.getDropDownListAccess().getGroup(), "rule__DropDownList__Group__0");
					put(grammarAccess.getDropDownListAccess().getGroup_4(), "rule__DropDownList__Group_4__0");
					put(grammarAccess.getDropDownListAccess().getGroup_5(), "rule__DropDownList__Group_5__0");
					put(grammarAccess.getCheckBoxAccess().getGroup(), "rule__CheckBox__Group__0");
					put(grammarAccess.getCheckBoxAccess().getGroup_3(), "rule__CheckBox__Group_3__0");
					put(grammarAccess.getCheckBoxAccess().getGroup_4(), "rule__CheckBox__Group_4__0");
					put(grammarAccess.getCheckBoxAccess().getGroup_5(), "rule__CheckBox__Group_5__0");
					put(grammarAccess.getDateUIComponentAccess().getGroup(), "rule__DateUIComponent__Group__0");
					put(grammarAccess.getDateUIComponentAccess().getGroup_3(), "rule__DateUIComponent__Group_3__0");
					put(grammarAccess.getDateUIComponentAccess().getGroup_4(), "rule__DateUIComponent__Group_4__0");
					put(grammarAccess.getDateUIComponentAccess().getGroup_5(), "rule__DateUIComponent__Group_5__0");
					put(grammarAccess.getTextInputAccess().getGroup(), "rule__TextInput__Group__0");
					put(grammarAccess.getTextInputAccess().getGroup_3(), "rule__TextInput__Group_3__0");
					put(grammarAccess.getTextInputAccess().getGroup_4(), "rule__TextInput__Group_4__0");
					put(grammarAccess.getTextInputAccess().getGroup_5(), "rule__TextInput__Group_5__0");
					put(grammarAccess.getTextAreaAccess().getGroup(), "rule__TextArea__Group__0");
					put(grammarAccess.getTextAreaAccess().getGroup_3(), "rule__TextArea__Group_3__0");
					put(grammarAccess.getTextAreaAccess().getGroup_4(), "rule__TextArea__Group_4__0");
					put(grammarAccess.getTextAreaAccess().getGroup_5(), "rule__TextArea__Group_5__0");
					put(grammarAccess.getTextAreaAccess().getGroup_6(), "rule__TextArea__Group_6__0");
					put(grammarAccess.getTelInputAccess().getGroup(), "rule__TelInput__Group__0");
					put(grammarAccess.getTelInputAccess().getGroup_3(), "rule__TelInput__Group_3__0");
					put(grammarAccess.getTelInputAccess().getGroup_4(), "rule__TelInput__Group_4__0");
					put(grammarAccess.getTelInputAccess().getGroup_5(), "rule__TelInput__Group_5__0");
					put(grammarAccess.getEmailInputAccess().getGroup(), "rule__EmailInput__Group__0");
					put(grammarAccess.getEmailInputAccess().getGroup_3(), "rule__EmailInput__Group_3__0");
					put(grammarAccess.getEmailInputAccess().getGroup_4(), "rule__EmailInput__Group_4__0");
					put(grammarAccess.getEmailInputAccess().getGroup_5(), "rule__EmailInput__Group_5__0");
					put(grammarAccess.getPasswordAccess().getGroup(), "rule__Password__Group__0");
					put(grammarAccess.getPasswordAccess().getGroup_3(), "rule__Password__Group_3__0");
					put(grammarAccess.getPasswordAccess().getGroup_4(), "rule__Password__Group_4__0");
					put(grammarAccess.getPasswordAccess().getGroup_5(), "rule__Password__Group_5__0");
					put(grammarAccess.getPasswordAccess().getGroup_6(), "rule__Password__Group_6__0");
					put(grammarAccess.getFileInputAccess().getGroup(), "rule__FileInput__Group__0");
					put(grammarAccess.getFileInputAccess().getGroup_3(), "rule__FileInput__Group_3__0");
					put(grammarAccess.getFileInputAccess().getGroup_4(), "rule__FileInput__Group_4__0");
					put(grammarAccess.getFileInputAccess().getGroup_5(), "rule__FileInput__Group_5__0");
					put(grammarAccess.getRefEntityAccess().getGroup(), "rule__RefEntity__Group__0");
					put(grammarAccess.getRefEntityAccess().getGroup_3(), "rule__RefEntity__Group_3__0");
					put(grammarAccess.getRefEntityAccess().getGroup_4(), "rule__RefEntity__Group_4__0");
					put(grammarAccess.getRefEntityAccess().getGroup_5(), "rule__RefEntity__Group_5__0");
					put(grammarAccess.getLoadValuesAccess().getGroup(), "rule__LoadValues__Group__0");
					put(grammarAccess.getLoadValuesAccess().getGroup_4(), "rule__LoadValues__Group_4__0");
					put(grammarAccess.getLoadValuesAccess().getGroup_5(), "rule__LoadValues__Group_5__0");
					put(grammarAccess.getAutocompleteComponentAccess().getGroup(), "rule__AutocompleteComponent__Group__0");
					put(grammarAccess.getAutocompleteComponentAccess().getGroup_3(), "rule__AutocompleteComponent__Group_3__0");
					put(grammarAccess.getAutocompleteComponentAccess().getGroup_4(), "rule__AutocompleteComponent__Group_4__0");
					put(grammarAccess.getEDoubleAccess().getGroup(), "rule__EDouble__Group__0");
					put(grammarAccess.getEDoubleAccess().getGroup_4(), "rule__EDouble__Group_4__0");
					put(grammarAccess.getEIntAccess().getGroup(), "rule__EInt__Group__0");
					put(grammarAccess.getPrimitiveDataTypeAccess().getGroup(), "rule__PrimitiveDataType__Group__0");
					put(grammarAccess.getNonPrimitiveDataTypeAccess().getGroup(), "rule__NonPrimitiveDataType__Group__0");
					put(grammarAccess.getErrorMessageAccess().getGroup(), "rule__ErrorMessage__Group__0");
					put(grammarAccess.getErrorMessageAccess().getGroup_2(), "rule__ErrorMessage__Group_2__0");
					put(grammarAccess.getRequiredAccess().getGroup(), "rule__Required__Group__0");
					put(grammarAccess.getMinLengthAccess().getGroup(), "rule__MinLength__Group__0");
					put(grammarAccess.getMaxLengthAccess().getGroup(), "rule__MaxLength__Group__0");
					put(grammarAccess.getLengthAccess().getGroup(), "rule__Length__Group__0");
					put(grammarAccess.getMinNumberAccess().getGroup(), "rule__MinNumber__Group__0");
					put(grammarAccess.getMinDateAccess().getGroup(), "rule__MinDate__Group__0");
					put(grammarAccess.getMaxNumberAccess().getGroup(), "rule__MaxNumber__Group__0");
					put(grammarAccess.getMaxNumberAccess().getGroup_3(), "rule__MaxNumber__Group_3__0");
					put(grammarAccess.getMaxDateAccess().getGroup(), "rule__MaxDate__Group__0");
					put(grammarAccess.getMaxDateAccess().getGroup_3(), "rule__MaxDate__Group_3__0");
					put(grammarAccess.getAcceptableValuesStringAccess().getGroup(), "rule__AcceptableValuesString__Group__0");
					put(grammarAccess.getAcceptableValuesStringAccess().getGroup_3(), "rule__AcceptableValuesString__Group_3__0");
					put(grammarAccess.getAcceptableValuesStringAccess().getGroup_3_1(), "rule__AcceptableValuesString__Group_3_1__0");
					put(grammarAccess.getAcceptableValuesDateAccess().getGroup(), "rule__AcceptableValuesDate__Group__0");
					put(grammarAccess.getAcceptableValuesDateAccess().getGroup_3(), "rule__AcceptableValuesDate__Group_3__0");
					put(grammarAccess.getAcceptableValuesDateAccess().getGroup_3_1(), "rule__AcceptableValuesDate__Group_3_1__0");
					put(grammarAccess.getStringPatternAccess().getGroup(), "rule__StringPattern__Group__0");
					put(grammarAccess.getDatePatternAccess().getGroup(), "rule__DatePattern__Group__0");
					put(grammarAccess.getDatePatternAccess().getGroup_3(), "rule__DatePattern__Group_3__0");
					put(grammarAccess.getNotEqualsAccess().getGroup(), "rule__NotEquals__Group__0");
					put(grammarAccess.getNotEqualsAccess().getGroup_3(), "rule__NotEquals__Group_3__0");
					put(grammarAccess.getNotEqualsAccess().getGroup_4(), "rule__NotEquals__Group_4__0");
					put(grammarAccess.getGreaterThanAccess().getGroup(), "rule__GreaterThan__Group__0");
					put(grammarAccess.getGreaterThanAccess().getGroup_5(), "rule__GreaterThan__Group_5__0");
					put(grammarAccess.getEqualsAccess().getGroup(), "rule__Equals__Group__0");
					put(grammarAccess.getEqualsAccess().getGroup_3(), "rule__Equals__Group_3__0");
					put(grammarAccess.getEqualsAccess().getGroup_4(), "rule__Equals__Group_4__0");
					put(grammarAccess.getLessThanAccess().getGroup(), "rule__LessThan__Group__0");
					put(grammarAccess.getLessThanAccess().getGroup_5(), "rule__LessThan__Group_5__0");
					put(grammarAccess.getLessThanAccess().getGroup_5_2(), "rule__LessThan__Group_5_2__0");
					put(grammarAccess.getAttributeArrayAccess().getGroup(), "rule__AttributeArray__Group__0");
					put(grammarAccess.getAttributeArrayAccess().getGroup_1(), "rule__AttributeArray__Group_1__0");
					put(grammarAccess.getAttributeArrayAccess().getGroup_1_2(), "rule__AttributeArray__Group_1_2__0");
					put(grammarAccess.getFieldSetAccess().getGroup(), "rule__FieldSet__Group__0");
					put(grammarAccess.getFieldSetAccess().getGroup_4(), "rule__FieldSet__Group_4__0");
					put(grammarAccess.getFieldSetAccess().getGroup_5(), "rule__FieldSet__Group_5__0");
					put(grammarAccess.getFieldSetAccess().getGroup_6(), "rule__FieldSet__Group_6__0");
					put(grammarAccess.getTabAccess().getGroup(), "rule__Tab__Group__0");
					put(grammarAccess.getTabAccess().getGroup_4(), "rule__Tab__Group_4__0");
					put(grammarAccess.getTabAccess().getGroup_5(), "rule__Tab__Group_5__0");
					put(grammarAccess.getTabAccess().getGroup_6(), "rule__Tab__Group_6__0");
					put(grammarAccess.getTabAccess().getGroup_6_2(), "rule__Tab__Group_6_2__0");
					put(grammarAccess.getGridAccess().getGroup(), "rule__Grid__Group__0");
					put(grammarAccess.getGridAccess().getGroup_4(), "rule__Grid__Group_4__0");
					put(grammarAccess.getGridAccess().getGroup_4_2(), "rule__Grid__Group_4_2__0");
					put(grammarAccess.getGridAccess().getGroup_5(), "rule__Grid__Group_5__0");
					put(grammarAccess.getAttributeSettingsAccess().getGroup(), "rule__AttributeSettings__Group__0");
					put(grammarAccess.getAttributeSettingsAccess().getGroup_3(), "rule__AttributeSettings__Group_3__0");
					put(grammarAccess.getLabelSettingsAccess().getGroup(), "rule__LabelSettings__Group__0");
					put(grammarAccess.getLabelSettingsAccess().getGroup_3(), "rule__LabelSettings__Group_3__0");
					put(grammarAccess.getErrorMessageSettingsAccess().getGroup(), "rule__ErrorMessageSettings__Group__0");
					put(grammarAccess.getErrorMessageSettingsAccess().getGroup_3(), "rule__ErrorMessageSettings__Group_3__0");
					put(grammarAccess.getErrorMessageSettingsAccess().getGroup_4(), "rule__ErrorMessageSettings__Group_4__0");
					put(grammarAccess.getFormSettingsAccess().getGroup(), "rule__FormSettings__Group__0");
					put(grammarAccess.getNoteSettingsAccess().getGroup(), "rule__NoteSettings__Group__0");
					put(grammarAccess.getNoteSettingsAccess().getGroup_3(), "rule__NoteSettings__Group_3__0");
					put(grammarAccess.getColorAccess().getGroup(), "rule__Color__Group__0");
					put(grammarAccess.getColorAccess().getGroup_2(), "rule__Color__Group_2__0");
					put(grammarAccess.getColorAccess().getGroup_3(), "rule__Color__Group_3__0");
					put(grammarAccess.getTableOverviewAccess().getGroup(), "rule__TableOverview__Group__0");
					put(grammarAccess.getTableOverviewAccess().getGroup_4(), "rule__TableOverview__Group_4__0");
					put(grammarAccess.getTableOverviewAccess().getGroup_5(), "rule__TableOverview__Group_5__0");
					put(grammarAccess.getTableOverviewAccess().getGroup_6(), "rule__TableOverview__Group_6__0");
					put(grammarAccess.getPaginationAccess().getGroup(), "rule__Pagination__Group__0");
					put(grammarAccess.getPaginationAccess().getGroup_3(), "rule__Pagination__Group_3__0");
					put(grammarAccess.getPaginationAccess().getGroup_3_3(), "rule__Pagination__Group_3_3__0");
					put(grammarAccess.getPaginationAccess().getGroup_4(), "rule__Pagination__Group_4__0");
					put(grammarAccess.getBusinessModelAccess().getLabelAssignment_2_1(), "rule__BusinessModel__LabelAssignment_2_1");
					put(grammarAccess.getBusinessModelAccess().getDescriptionAssignment_3_1(), "rule__BusinessModel__DescriptionAssignment_3_1");
					put(grammarAccess.getBusinessModelAccess().getValidationclassesAssignment_4_0(), "rule__BusinessModel__ValidationclassesAssignment_4_0");
					put(grammarAccess.getBusinessModelAccess().getValidationclassesAssignment_4_1(), "rule__BusinessModel__ValidationclassesAssignment_4_1");
					put(grammarAccess.getValidationClassAccess().getNameAssignment_1(), "rule__ValidationClass__NameAssignment_1");
					put(grammarAccess.getValidationClassAccess().getLabelAssignment_3_1(), "rule__ValidationClass__LabelAssignment_3_1");
					put(grammarAccess.getValidationClassAccess().getClassattributeAssignment_4_0(), "rule__ValidationClass__ClassattributeAssignment_4_0");
					put(grammarAccess.getValidationClassAccess().getClassattributeAssignment_4_1(), "rule__ValidationClass__ClassattributeAssignment_4_1");
					put(grammarAccess.getValidationClassAccess().getClassruleAssignment_5_0(), "rule__ValidationClass__ClassruleAssignment_5_0");
					put(grammarAccess.getValidationClassAccess().getClassruleAssignment_5_1(), "rule__ValidationClass__ClassruleAssignment_5_1");
					put(grammarAccess.getValidationClassAccess().getFormlayoutAssignment_6_0(), "rule__ValidationClass__FormlayoutAssignment_6_0");
					put(grammarAccess.getValidationClassAccess().getFormlayoutAssignment_6_1(), "rule__ValidationClass__FormlayoutAssignment_6_1");
					put(grammarAccess.getValidationClassAccess().getAdditionalSettingsAssignment_7_0(), "rule__ValidationClass__AdditionalSettingsAssignment_7_0");
					put(grammarAccess.getValidationClassAccess().getAdditionalSettingsAssignment_7_1(), "rule__ValidationClass__AdditionalSettingsAssignment_7_1");
					put(grammarAccess.getValidationClassAccess().getOverviewsettingsAssignment_8(), "rule__ValidationClass__OverviewsettingsAssignment_8");
					put(grammarAccess.getClassAttributeAccess().getNameAssignment_0(), "rule__ClassAttribute__NameAssignment_0");
					put(grammarAccess.getClassAttributeAccess().getLabelAssignment_2_1(), "rule__ClassAttribute__LabelAssignment_2_1");
					put(grammarAccess.getClassAttributeAccess().getAttributetypeAssignment_3(), "rule__ClassAttribute__AttributetypeAssignment_3");
					put(grammarAccess.getClassAttributeAccess().getMasterAssignment_4(), "rule__ClassAttribute__MasterAssignment_4");
					put(grammarAccess.getClassAttributeAccess().getIsClassRepresentingAssignment_5(), "rule__ClassAttribute__IsClassRepresentingAssignment_5");
					put(grammarAccess.getClassAttributeAccess().getAttributeruleAssignment_6_0(), "rule__ClassAttribute__AttributeruleAssignment_6_0");
					put(grammarAccess.getClassAttributeAccess().getAttributeruleAssignment_6_1(), "rule__ClassAttribute__AttributeruleAssignment_6_1");
					put(grammarAccess.getOverviewSettingsAccess().getTableoverviewAssignment_3(), "rule__OverviewSettings__TableoverviewAssignment_3");
					put(grammarAccess.getAttributeTypeAccess().getAttributeDataTypeAssignment_1(), "rule__AttributeType__AttributeDataTypeAssignment_1");
					put(grammarAccess.getAttributeTypeAccess().getUiComponentAssignment_2(), "rule__AttributeType__UiComponentAssignment_2");
					put(grammarAccess.getNumericUIComponentAccess().getTooltipAssignment_3_1(), "rule__NumericUIComponent__TooltipAssignment_3_1");
					put(grammarAccess.getNumericUIComponentAccess().getNoteAssignment_4_1(), "rule__NumericUIComponent__NoteAssignment_4_1");
					put(grammarAccess.getNumericUIComponentAccess().getDefaultValueAssignment_5_1(), "rule__NumericUIComponent__DefaultValueAssignment_5_1");
					put(grammarAccess.getNumericUIComponentAccess().getComponentTypeAssignment_6_1(), "rule__NumericUIComponent__ComponentTypeAssignment_6_1");
					put(grammarAccess.getRadioButtonAccess().getTooltipAssignment_3_1(), "rule__RadioButton__TooltipAssignment_3_1");
					put(grammarAccess.getRadioButtonAccess().getNoteAssignment_4_1(), "rule__RadioButton__NoteAssignment_4_1");
					put(grammarAccess.getRadioButtonAccess().getOrientationAssignment_5_1(), "rule__RadioButton__OrientationAssignment_5_1");
					put(grammarAccess.getDropDownListAccess().getIsMultiSelectAssignment_3(), "rule__DropDownList__IsMultiSelectAssignment_3");
					put(grammarAccess.getDropDownListAccess().getTooltipAssignment_4_1(), "rule__DropDownList__TooltipAssignment_4_1");
					put(grammarAccess.getDropDownListAccess().getNoteAssignment_5_1(), "rule__DropDownList__NoteAssignment_5_1");
					put(grammarAccess.getCheckBoxAccess().getTooltipAssignment_3_1(), "rule__CheckBox__TooltipAssignment_3_1");
					put(grammarAccess.getCheckBoxAccess().getNoteAssignment_4_1(), "rule__CheckBox__NoteAssignment_4_1");
					put(grammarAccess.getCheckBoxAccess().getOrientationAssignment_5_1(), "rule__CheckBox__OrientationAssignment_5_1");
					put(grammarAccess.getDateUIComponentAccess().getTooltipAssignment_3_1(), "rule__DateUIComponent__TooltipAssignment_3_1");
					put(grammarAccess.getDateUIComponentAccess().getNoteAssignment_4_1(), "rule__DateUIComponent__NoteAssignment_4_1");
					put(grammarAccess.getDateUIComponentAccess().getTypeAssignment_5_1(), "rule__DateUIComponent__TypeAssignment_5_1");
					put(grammarAccess.getTextInputAccess().getTooltipAssignment_3_1(), "rule__TextInput__TooltipAssignment_3_1");
					put(grammarAccess.getTextInputAccess().getNoteAssignment_4_1(), "rule__TextInput__NoteAssignment_4_1");
					put(grammarAccess.getTextInputAccess().getPlaceHolderAssignment_5_1(), "rule__TextInput__PlaceHolderAssignment_5_1");
					put(grammarAccess.getTextAreaAccess().getTooltipAssignment_3_1(), "rule__TextArea__TooltipAssignment_3_1");
					put(grammarAccess.getTextAreaAccess().getNoteAssignment_4_1(), "rule__TextArea__NoteAssignment_4_1");
					put(grammarAccess.getTextAreaAccess().getPlaceHolderAssignment_5_1(), "rule__TextArea__PlaceHolderAssignment_5_1");
					put(grammarAccess.getTextAreaAccess().getNumOfRowsAssignment_6_1(), "rule__TextArea__NumOfRowsAssignment_6_1");
					put(grammarAccess.getTelInputAccess().getTooltipAssignment_3_1(), "rule__TelInput__TooltipAssignment_3_1");
					put(grammarAccess.getTelInputAccess().getNoteAssignment_4_1(), "rule__TelInput__NoteAssignment_4_1");
					put(grammarAccess.getTelInputAccess().getPlaceHolderAssignment_5_1(), "rule__TelInput__PlaceHolderAssignment_5_1");
					put(grammarAccess.getEmailInputAccess().getTooltipAssignment_3_1(), "rule__EmailInput__TooltipAssignment_3_1");
					put(grammarAccess.getEmailInputAccess().getNoteAssignment_4_1(), "rule__EmailInput__NoteAssignment_4_1");
					put(grammarAccess.getEmailInputAccess().getPlaceHolderAssignment_5_1(), "rule__EmailInput__PlaceHolderAssignment_5_1");
					put(grammarAccess.getPasswordAccess().getTooltipAssignment_3_1(), "rule__Password__TooltipAssignment_3_1");
					put(grammarAccess.getPasswordAccess().getNoteAssignment_4_1(), "rule__Password__NoteAssignment_4_1");
					put(grammarAccess.getPasswordAccess().getPlaceHolderAssignment_5_1(), "rule__Password__PlaceHolderAssignment_5_1");
					put(grammarAccess.getPasswordAccess().getVisibleAssignment_6_1(), "rule__Password__VisibleAssignment_6_1");
					put(grammarAccess.getFileInputAccess().getTooltipAssignment_3_1(), "rule__FileInput__TooltipAssignment_3_1");
					put(grammarAccess.getFileInputAccess().getNoteAssignment_4_1(), "rule__FileInput__NoteAssignment_4_1");
					put(grammarAccess.getFileInputAccess().getButtonPositionAssignment_5_1(), "rule__FileInput__ButtonPositionAssignment_5_1");
					put(grammarAccess.getRefEntityAccess().getTooltipAssignment_3_1(), "rule__RefEntity__TooltipAssignment_3_1");
					put(grammarAccess.getRefEntityAccess().getNoteAssignment_4_1(), "rule__RefEntity__NoteAssignment_4_1");
					put(grammarAccess.getRefEntityAccess().getIsSingeValueAssignment_5_1(), "rule__RefEntity__IsSingeValueAssignment_5_1");
					put(grammarAccess.getLoadValuesAccess().getIsMultiSelectAssignment_1(), "rule__LoadValues__IsMultiSelectAssignment_1");
					put(grammarAccess.getLoadValuesAccess().getTooltipAssignment_4_1(), "rule__LoadValues__TooltipAssignment_4_1");
					put(grammarAccess.getLoadValuesAccess().getNoteAssignment_5_1(), "rule__LoadValues__NoteAssignment_5_1");
					put(grammarAccess.getAutocompleteComponentAccess().getTooltipAssignment_3_1(), "rule__AutocompleteComponent__TooltipAssignment_3_1");
					put(grammarAccess.getAutocompleteComponentAccess().getNoteAssignment_4_1(), "rule__AutocompleteComponent__NoteAssignment_4_1");
					put(grammarAccess.getPrimitiveDataTypeAccess().getTypeAssignment_1(), "rule__PrimitiveDataType__TypeAssignment_1");
					put(grammarAccess.getPrimitiveDataTypeAccess().getIsCollectionAssignment_2(), "rule__PrimitiveDataType__IsCollectionAssignment_2");
					put(grammarAccess.getNonPrimitiveDataTypeAccess().getTypeAssignment_0(), "rule__NonPrimitiveDataType__TypeAssignment_0");
					put(grammarAccess.getNonPrimitiveDataTypeAccess().getIsCollectionAssignment_1(), "rule__NonPrimitiveDataType__IsCollectionAssignment_1");
					put(grammarAccess.getErrorMessageAccess().getMessageAssignment_2_1(), "rule__ErrorMessage__MessageAssignment_2_1");
					put(grammarAccess.getRequiredAccess().getAttributeRuleErrorMessageAssignment_2(), "rule__Required__AttributeRuleErrorMessageAssignment_2");
					put(grammarAccess.getMinLengthAccess().getValueAssignment_2(), "rule__MinLength__ValueAssignment_2");
					put(grammarAccess.getMinLengthAccess().getAttributeRuleErrorMessageAssignment_3(), "rule__MinLength__AttributeRuleErrorMessageAssignment_3");
					put(grammarAccess.getMaxLengthAccess().getValueAssignment_2(), "rule__MaxLength__ValueAssignment_2");
					put(grammarAccess.getMaxLengthAccess().getAttributeRuleErrorMessageAssignment_3(), "rule__MaxLength__AttributeRuleErrorMessageAssignment_3");
					put(grammarAccess.getLengthAccess().getValueAssignment_2(), "rule__Length__ValueAssignment_2");
					put(grammarAccess.getLengthAccess().getAttributeRuleErrorMessageAssignment_3(), "rule__Length__AttributeRuleErrorMessageAssignment_3");
					put(grammarAccess.getMinNumberAccess().getValueAssignment_2(), "rule__MinNumber__ValueAssignment_2");
					put(grammarAccess.getMinNumberAccess().getAttributeRuleErrorMessageAssignment_3(), "rule__MinNumber__AttributeRuleErrorMessageAssignment_3");
					put(grammarAccess.getMinDateAccess().getValueAssignment_2(), "rule__MinDate__ValueAssignment_2");
					put(grammarAccess.getMinDateAccess().getAttributeRuleErrorMessageAssignment_3(), "rule__MinDate__AttributeRuleErrorMessageAssignment_3");
					put(grammarAccess.getMaxNumberAccess().getValueAssignment_3_1(), "rule__MaxNumber__ValueAssignment_3_1");
					put(grammarAccess.getMaxNumberAccess().getAttributeRuleErrorMessageAssignment_4(), "rule__MaxNumber__AttributeRuleErrorMessageAssignment_4");
					put(grammarAccess.getMaxDateAccess().getValueAssignment_3_1(), "rule__MaxDate__ValueAssignment_3_1");
					put(grammarAccess.getMaxDateAccess().getAttributeRuleErrorMessageAssignment_4(), "rule__MaxDate__AttributeRuleErrorMessageAssignment_4");
					put(grammarAccess.getAcceptableValuesStringAccess().getValuesAssignment_3_0(), "rule__AcceptableValuesString__ValuesAssignment_3_0");
					put(grammarAccess.getAcceptableValuesStringAccess().getValuesAssignment_3_1_1(), "rule__AcceptableValuesString__ValuesAssignment_3_1_1");
					put(grammarAccess.getAcceptableValuesStringAccess().getAttributeRuleErrorMessageAssignment_4(), "rule__AcceptableValuesString__AttributeRuleErrorMessageAssignment_4");
					put(grammarAccess.getAcceptableValuesDateAccess().getValuesAssignment_3_0(), "rule__AcceptableValuesDate__ValuesAssignment_3_0");
					put(grammarAccess.getAcceptableValuesDateAccess().getValuesAssignment_3_1_1(), "rule__AcceptableValuesDate__ValuesAssignment_3_1_1");
					put(grammarAccess.getAcceptableValuesDateAccess().getAttributeRuleErrorMessageAssignment_4(), "rule__AcceptableValuesDate__AttributeRuleErrorMessageAssignment_4");
					put(grammarAccess.getStringPatternAccess().getValueAssignment_2(), "rule__StringPattern__ValueAssignment_2");
					put(grammarAccess.getStringPatternAccess().getAttributeRuleErrorMessageAssignment_3(), "rule__StringPattern__AttributeRuleErrorMessageAssignment_3");
					put(grammarAccess.getDatePatternAccess().getValueAssignment_3_1(), "rule__DatePattern__ValueAssignment_3_1");
					put(grammarAccess.getDatePatternAccess().getAttributeRuleErrorMessageAssignment_4(), "rule__DatePattern__AttributeRuleErrorMessageAssignment_4");
					put(grammarAccess.getNotEqualsAccess().getClassRuleErrorMessageAssignment_3_1(), "rule__NotEquals__ClassRuleErrorMessageAssignment_3_1");
					put(grammarAccess.getNotEqualsAccess().getAttributearrayAssignment_4_1(), "rule__NotEquals__AttributearrayAssignment_4_1");
					put(grammarAccess.getGreaterThanAccess().getClassattributeAssignment_3(), "rule__GreaterThan__ClassattributeAssignment_3");
					put(grammarAccess.getGreaterThanAccess().getClassRuleErrorMessageAssignment_4(), "rule__GreaterThan__ClassRuleErrorMessageAssignment_4");
					put(grammarAccess.getGreaterThanAccess().getAttributearrayAssignment_5_1(), "rule__GreaterThan__AttributearrayAssignment_5_1");
					put(grammarAccess.getGreaterThanAccess().getAttributearrayAssignment_5_2(), "rule__GreaterThan__AttributearrayAssignment_5_2");
					put(grammarAccess.getEqualsAccess().getClassRuleErrorMessageAssignment_3_1(), "rule__Equals__ClassRuleErrorMessageAssignment_3_1");
					put(grammarAccess.getEqualsAccess().getAttributearrayAssignment_4_1(), "rule__Equals__AttributearrayAssignment_4_1");
					put(grammarAccess.getLessThanAccess().getClassattributeAssignment_3(), "rule__LessThan__ClassattributeAssignment_3");
					put(grammarAccess.getLessThanAccess().getClassRuleErrorMessageAssignment_4(), "rule__LessThan__ClassRuleErrorMessageAssignment_4");
					put(grammarAccess.getLessThanAccess().getAttributearrayAssignment_5_1(), "rule__LessThan__AttributearrayAssignment_5_1");
					put(grammarAccess.getLessThanAccess().getAttributearrayAssignment_5_2_1(), "rule__LessThan__AttributearrayAssignment_5_2_1");
					put(grammarAccess.getAttributeArrayAccess().getAttributesAssignment_1_1(), "rule__AttributeArray__AttributesAssignment_1_1");
					put(grammarAccess.getAttributeArrayAccess().getAttributesAssignment_1_2_1(), "rule__AttributeArray__AttributesAssignment_1_2_1");
					put(grammarAccess.getFieldSetAccess().getNameAssignment_2(), "rule__FieldSet__NameAssignment_2");
					put(grammarAccess.getFieldSetAccess().getLegendAssignment_4_1(), "rule__FieldSet__LegendAssignment_4_1");
					put(grammarAccess.getFieldSetAccess().getAttributearrayAssignment_5_1(), "rule__FieldSet__AttributearrayAssignment_5_1");
					put(grammarAccess.getFieldSetAccess().getAttributearrayAssignment_5_2(), "rule__FieldSet__AttributearrayAssignment_5_2");
					put(grammarAccess.getFieldSetAccess().getLayoutsAssignment_6_0(), "rule__FieldSet__LayoutsAssignment_6_0");
					put(grammarAccess.getFieldSetAccess().getLayoutsAssignment_6_1(), "rule__FieldSet__LayoutsAssignment_6_1");
					put(grammarAccess.getTabAccess().getNameAssignment_2(), "rule__Tab__NameAssignment_2");
					put(grammarAccess.getTabAccess().getLabelAssignment_4_1(), "rule__Tab__LabelAssignment_4_1");
					put(grammarAccess.getTabAccess().getAttributearrayAssignment_5_1(), "rule__Tab__AttributearrayAssignment_5_1");
					put(grammarAccess.getTabAccess().getAttributearrayAssignment_5_2(), "rule__Tab__AttributearrayAssignment_5_2");
					put(grammarAccess.getTabAccess().getLayoutsAssignment_6_1(), "rule__Tab__LayoutsAssignment_6_1");
					put(grammarAccess.getTabAccess().getLayoutsAssignment_6_2_1(), "rule__Tab__LayoutsAssignment_6_2_1");
					put(grammarAccess.getGridAccess().getNameAssignment_2(), "rule__Grid__NameAssignment_2");
					put(grammarAccess.getGridAccess().getAttributearrayAssignment_4_1(), "rule__Grid__AttributearrayAssignment_4_1");
					put(grammarAccess.getGridAccess().getAttributearrayAssignment_4_2_1(), "rule__Grid__AttributearrayAssignment_4_2_1");
					put(grammarAccess.getGridAccess().getLayoutsAssignment_5_0(), "rule__Grid__LayoutsAssignment_5_0");
					put(grammarAccess.getGridAccess().getLayoutsAssignment_5_1(), "rule__Grid__LayoutsAssignment_5_1");
					put(grammarAccess.getAttributeSettingsAccess().getPresentationAssignment_3_1(), "rule__AttributeSettings__PresentationAssignment_3_1");
					put(grammarAccess.getLabelSettingsAccess().getPositionAssignment_3_1(), "rule__LabelSettings__PositionAssignment_3_1");
					put(grammarAccess.getErrorMessageSettingsAccess().getPositionAssignment_3_1(), "rule__ErrorMessageSettings__PositionAssignment_3_1");
					put(grammarAccess.getErrorMessageSettingsAccess().getColorAssignment_4_1(), "rule__ErrorMessageSettings__ColorAssignment_4_1");
					put(grammarAccess.getFormSettingsAccess().getAutoCompleteAssignment_1(), "rule__FormSettings__AutoCompleteAssignment_1");
					put(grammarAccess.getNoteSettingsAccess().getPositionAssignment_3_1(), "rule__NoteSettings__PositionAssignment_3_1");
					put(grammarAccess.getColorAccess().getRedAssignment_2_0(), "rule__Color__RedAssignment_2_0");
					put(grammarAccess.getColorAccess().getGreenAssignment_3_0(), "rule__Color__GreenAssignment_3_0");
					put(grammarAccess.getColorAccess().getBlueAssignment_4(), "rule__Color__BlueAssignment_4");
					put(grammarAccess.getTableOverviewAccess().getNameAssignment_2(), "rule__TableOverview__NameAssignment_2");
					put(grammarAccess.getTableOverviewAccess().getHeightAssignment_4_1(), "rule__TableOverview__HeightAssignment_4_1");
					put(grammarAccess.getTableOverviewAccess().getWidthAssignment_5_1(), "rule__TableOverview__WidthAssignment_5_1");
					put(grammarAccess.getTableOverviewAccess().getTitleAssignment_6_1(), "rule__TableOverview__TitleAssignment_6_1");
					put(grammarAccess.getTableOverviewAccess().getPagingAssignment_7(), "rule__TableOverview__PagingAssignment_7");
					put(grammarAccess.getPaginationAccess().getPossibleNumberOfShownRowsAssignment_3_2(), "rule__Pagination__PossibleNumberOfShownRowsAssignment_3_2");
					put(grammarAccess.getPaginationAccess().getPossibleNumberOfShownRowsAssignment_3_3_1(), "rule__Pagination__PossibleNumberOfShownRowsAssignment_3_3_1");
					put(grammarAccess.getPaginationAccess().getDefaultNumOfShownRowsAssignment_4_1(), "rule__Pagination__DefaultNumOfShownRowsAssignment_4_1");
				}
			};
		}
		return nameMappings.get(element);
	}

	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			InternalFormValDSLParser typedParser = (InternalFormValDSLParser) parser;
			typedParser.entryRuleBusinessModel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public FormValDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(FormValDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
