/*
 * generated by Xtext
 */
package org.xtext.example.domij;

import org.eclipse.emf.common.util.EList;
import org.eclipse.xtext.naming.IQualifiedNameProvider;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ErDslRuntimeModule extends org.xtext.example.domij.AbstractErDslRuntimeModule {

	@Override
    public Class<? extends IQualifiedNameProvider> bindIQualifiedNameProvider() {
        return ErDslQNP.class;
    }

}
