/**
 * generated by Xtext 2.9.1
 */
package mist.classgen.generate.generator;

import org.xtext.example.mydsl.AbstractFormValDSLRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class FormValidationRuntimeModule extends AbstractFormValDSLRuntimeModule {
}
